name: MineCombat
main: MineCombat\MainLoader
version: InDev
api: [1.1.0]
author: MK
description: Plugin for PIDE Event Server
website: http://cafe.naver.com/minecraftpe
commands:
 mc:
  description: MineCombat main command
  usage: "Usage: /mc, In PROGRESS"